{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "units", "default": 8, "conditions": [], "values": [8, 16, 32], "ordered": true}}], "values": {"units": 8}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 54, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.FailedPreconditionError: Graph execution error:\n\nDetected at node 'model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2' defined at (most recent call last):\n    File \"C:\\Users\\Erwin\\.conda\\envs\\msub-tfx\\lib\\runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\Erwin\\.conda\\envs\\msub-tfx\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n      app.start()\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelapp.py\", line 725, in start\n      self.io_loop.start()\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\Erwin\\.conda\\envs\\msub-tfx\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"C:\\Users\\Erwin\\.conda\\envs\\msub-tfx\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"C:\\Users\\Erwin\\.conda\\envs\\msub-tfx\\lib\\asyncio\\events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n      await result\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\Erwin\\AppData\\Local\\Temp\\ipykernel_15136\\3813298364.py\", line 13, in <cell line: 13>\n      interactive_context.run(tuner)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\orchestration\\experimental\\interactive\\notebook_utils.py\", line 31, in run_if_ipython\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\orchestration\\experimental\\interactive\\interactive_context.py\", line 164, in run\n      execution_id = launcher.launch().execution_id\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\orchestration\\launcher\\base_component_launcher.py\", line 206, in launch\n      self._run_executor(execution_decision.execution_id,\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\orchestration\\launcher\\in_process_component_launcher.py\", line 73, in _run_executor\n      executor.Do(\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\components\\tuner\\executor.py\", line 122, in Do\n      tuner = search(input_dict, exec_properties, self._get_tmp_dir())\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\tfx\\components\\tuner\\executor.py\", line 100, in search\n      tuner_fn_result = tuner_fn(fn_args)\n    File \"D:\\ProjectJupiterLab\\submission-tweet\\tweets_tuner.py\", line 108, in tuner_fn\n      tuner.search(train_set, epochs=5, validation_data=(val_set))\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 230, in search\n      self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n      self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n      results = self.run_trial(trial, *fit_args, **fit_kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n      obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n      results = self.hypermodel.fit(hp, model, *args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n      return model.fit(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 1564, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step\n      outputs = model.train_step(data)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 993, in train_step\n      y_pred = self(x, training=True)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\training.py\", line 557, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\functional.py\", line 510, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\functional.py\", line 667, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\layers\\preprocessing\\text_vectorization.py\", line 610, in call\n      lookup_data = self._lookup_layer(inputs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\engine\\base_layer.py\", line 1097, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\layers\\preprocessing\\index_lookup.py\", line 743, in call\n      lookups = tf.ragged.map_flat_values(self._lookup_dense, inputs)\n    File \"C:\\Users\\Erwin\\AppData\\Roaming\\Python\\Python38\\site-packages\\keras\\layers\\preprocessing\\index_lookup.py\", line 781, in _lookup_dense\n      lookups = self.lookup_table.lookup(inputs)\nNode: 'model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2'\nTable not initialized.\n\t [[{{node model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2}}]] [Op:__inference_train_function_1331891]\n"}